import { SocksProxyAgent } from "socks-proxy-agent"
import { HTMLElement } from "node-html-parser"
import { IntfRequestParams } from "./request"

export enum enuDomains {
    farsnews = "farsnews",
    hamshahrionline = "hamshahrionline",
    irna = "irna",
    mashreghnews = "mashreghnews",
    khabaronline = "khabaronline",
    mehrnews = "mehrnews",
    aftabnews = "aftabnews",
    seratnews = "seratnews",
    rajanews = "rajanews",
    alef = "alef",
    mojnews = "mojnews",
    iqna = "iqna",
    isna = "isna",
    ilna = "ilna",
    imna = "imna",
    shana = "shana",
    ana = "ana",
    chtn = "chtn",
    tasnim = "tasnim",
    tabnak = "tabnak",
    spnfa = "spnfa",
    sputnikaf = "sputnikaf",
    pana = "pana",
    ibna = "ibna",
    iana = "iana",
    snn = "snn",
    yjc = "yjc",
    virgool = "virgool",
    baharnews = "baharnews",
    khamenei = "khamenei",
    citna = "citna",
    rokna = "rokna",
    itna = "itna",
    ninisite = "ninisite",
    ictnews = "ictnews",
    asriran = "asriran",
    jahannews = "jahannews",
    varzesh3 = "varzesh3",
    tarafdari = "tarafdari",
    lastsecond = "lastsecond",

    fardanews = "fardanews",
    bultannews = "bultannews",
    boursenews = "boursenews",
    shahr = "shahr",
    fararu = "fararu",
    parsine = "parsine",
    shianews = "shianews",
    hawzahnews = "hawzahnews",
    khabarfoori = "khabarfoori",
    bartarinha = "bartarinha",
    iribnews = "iribnews",
    mizanonline = "mizanonline",
    kayhan = "kayhan",
    basijnews = "basijnews",
    shahraranews = "shahraranews",
    rasanews = "rasanews",
    didarnews = "didarnews",
    faradeed = "faradeed",
    niniban = "niniban",
    roozno = "roozno",
    noandish = "noandish",
    javanonline = "javanonline",
    aghigh = "aghigh",
    paydarymelli = "paydarymelli",
    danakhabar = "danakhabar",
    niknews = "niknews",
    iraneconomist = "iraneconomist",
    barghnews = "barghnews",
    shohadayeiran = "shohadayeiran",
    sedayiran = "sedayiran",
    tejaratonline = "tejaratonline",
    sarmadnews = "sarmadnews",
    goftareno = "goftareno",
    tejaratemrouz = "tejaratemrouz",
    vananews = "vananews",
    tabnakbato = "tabnakbato",
    shoaresal = "shoaresal",
    bankdariirani = "bankdariirani",
    tebyan = "tebyan",
    digikala = "digikala",
    romanman = "romanman",
    webhostingtalk = "webhostingtalk",
    barnamenevis = "barnamenevis",
    p30world = "p30world",
    tarfandestan = "tarfandestan",
    boursy = "boursy",
    soft98 = "soft98",
    persiantools = "persiantools",
    majidonline = "majidonline",
    lioncomputer = "lioncomputer",
    wikifa = "wikifa",
    yekpezeshk = "yekpezeshk",
    digiato = "digiato",
    blogir = "blogir",
    yektanet = "yektanet",
    bazmineh = "bazmineh",
    namnak = "namnak",
    beytoote = "beytoote",
    blogsky = "blogsky",
    technolife = "technolife",
    sid = "sid",
    sakhtafzarmag = "sakhtafzarmag",
    bazicenter = "bazicenter",
    wppersian = "wppersian",
    joomlafarsi = "joomlafarsi",
    moshaver = "moshaver",
    oghyanos = "oghyanos",
    naghdfarsi = "naghdfarsi",
    arzdigital = "arzdigital",
    ramzarz = "ramzarz",
    donyaeeqtesad = "donyaeeqtesad",
    eghtesadonline = "eghtesadonline",
    sabakhabar = "sabakhabar",
    avayekhazar = "avayekhazar",
    khabarvarzeshi = "khabarvarzeshi",
    sena = "sena",
    mefda = "mefda",
    iscanews = "iscanews",
    behzisti = "behzisti",
    tahlilbazaar = "tahlilbazaar",
    kanoonnews = "kanoonnews",
    imereport = "imereport",
    oipf = "oipf",
    salameno = "salameno",
    tehrannews = "tehrannews",
    tahririeh = "tahririeh",
    atiyeonline = "atiyeonline",
    salamatnews = "salamatnews",
    eximnews = "eximnews",
    payamekhanevadeh = "payamekhanevadeh",
    qudsonline = "qudsonline",
    karafarinnews = "karafarinnews",
    bidarbourse = "bidarbourse",
    shahryarnews = "shahryarnews",
    sahebkhabar = "sahebkhabar",
    saat24 = "saat24",
    zoomit = "zoomit",
    farhangemrooz = "farhangemrooz",
    cinemapress = "cinemapress",
    ifsm = "ifsm",
    sedayebourse = "sedayebourse",
    donyayekhodro = "donyayekhodro",
    chamedanmag = "chamedanmag",
    irasin = "irasin",
    tebna = "tebna",
    foodpress = "foodpress",
    fardayeeghtesad = "fardayeeghtesad",
    radareghtesad = "radareghtesad",
    karajemrouz = "karajemrouz",
    titre20 = "titre20",
    khabaredagh = "khabaredagh",
    bazarnews = "bazarnews",
    khordad = "khordad",
    wikihoghoogh = "wikihoghoogh",
    wikivoyage = "wikivoyage",
    wikibooks = "wikibooks",
    wikisource = "wikisource",
    arakhabar = "arakhabar",
    nabznaft = "nabznaft",
    diibache = "diibache",
    mana = "mana",
    rahbordemoaser = "rahbordemoaser",
    mednews = "mednews",
    khatebazar = "khatebazar",
    tabnakjavan = "tabnakjavan",
    dsport = "dsport",
    farhangesadid = "farhangesadid",
    basna = "basna",
    jomhouriat = "jomhouriat",
    titrekootah = "titrekootah",
    didgahemrooz = "didgahemrooz",
    wikigardi = "wikigardi",
    jahanemana = "jahanemana",
    shomavaeghtesad = "shomavaeghtesad",
    borna = "borna",
    ecoiran = "ecoiran",
    eghtesadnews = "eghtesadnews",
    sharghdaily = "sharghdaily",
    nasim = "nasim",
    afkarnews = "afkarnews",
    etemadonline = "etemadonline",
    gostaresh = "gostaresh",
    moniban = "moniban",
    honaronline = "honaronline",
    mosalasonline = "mosalasonline",
    tejaratefarda = "tejaratefarda",
    fartaknews = "fartaknews",
    shayanews = "shayanews",
    cann = "cann",
    shomanews = "shomanews",
    mostaghelonline = "mostaghelonline",
    iranart = "iranart",
    neshanonline = "neshanonline",
    chabokonline = "chabokonline",
    toseeirani = "toseeirani",
    baeghtesad = "baeghtesad",
    mamlekatonline = "mamlekatonline",
    khanefootball = "khanefootball",
    honarmrooz = "honarmrooz",
    moroornews = "moroornews",
    keshavarzplus = "keshavarzplus",
    armanmeli = "armanmeli",
    farazdaily = "farazdaily",
    arshehonline = "arshehonline",
    jadidpress = "jadidpress",
    khodrotak = "khodrotak",
    zenhar = "zenhar",
    ayandnews = "ayandnews",
    tapesh3 = "tapesh3",
    panjahopanjonline = "panjahopanjonline",
    donyayemadan = "donyayemadan",
    taraznameheghtesad = "taraznameheghtesad",
    bazarebours = "bazarebours",
    panjere = "panjere",
    econegar = "econegar",
    rasadeghtesadi = "rasadeghtesadi",
    gashtaninews = "gashtaninews",
    revayatnameh = "revayatnameh",
    sornakhabar = "sornakhabar",
    jamejamonline = "jamejamonline",
    pansadonavadohasht = "pansadonavadohasht",
    ofoghnews = "ofoghnews",
    snapp = "snapp",
    snappfood = "snappfood",
    snapptrip = "snapptrip",
    nobitex = "nobitex",
    snappmarket = "snappmarket",
    flightio = "flightio",
    namava = "namava",
    achareh = "achareh",
    aparat = "aparat",
    taaghche = "taaghche",
    jabama = "jabama",
    fidibo = "fidibo",
    jobinja = "jobinja",
    rayamarketing = "rayamarketing",
    miare = "miare",
    abantether = "abantether",
    okala = "okala",
    faradars = "faradars",
    limoonad = "limoonad",
    kalleh = "kalleh",
    chetor = "chetor",
    madarsho = "madarsho",
    filimoshot = "filimoshot",
    sarakco = "sarakco",
    avalpardakht = "avalpardakht",
    maktabkhooneh = "maktabkhooneh",
    sevenlearn = "sevenlearn",
    modireweb = "modireweb",
    doctoreto = "doctoreto",
    bookland = "bookland",
    iranhotelonline = "iranhotelonline",
    bonyadvokala = "bonyadvokala",
    apademy = "apademy",
    iranicard = "iranicard",
    hamrah = "hamrah",
    asiatech = "asiatech",
    ponisha = "ponisha",
    trip = "trip",
    parshistory = "parshistory",
    rawanshenas = "rawanshenas",
    telescope = "telescope",
    mendellab = "mendellab",
    faab = "faab",
    wikiravan = "wikiravan",
    arzfi = "arzfi",
    gishniz = "gishniz",
    chemibazar = "chemibazar",
    mehrdadcivil = "mehrdadcivil",
    sakkook = "sakkook",
    bestfarsi = "bestfarsi",
    hamgardi = "hamgardi",
    novin = "novin",
    zibamoon = "zibamoon",
    iranacademy = "iranacademy",
    digistyle = "digistyle",
    iranserver = "iranserver",
    parscoders = "parscoders",
    liangroup = "liangroup",
    honareseda = "honareseda",
    malltina = "malltina",
    webpouya = "webpouya",
    followshe = "followshe",
    watereng = "watereng",
    iraneurope = "iraneurope",
    emalls = "emalls",
    shereno = "shereno",
    scorize = "scorize",
    exbito = "exbito",
    tarjomic = "tarjomic",
    ompfinex = "ompfinex",
    sesotweb = "sesotweb",
    amuzeshtak = "amuzeshtak",
    tehranserver = "tehranserver",
    iranestekhdam = "iranestekhdam",
    sinapub = "sinapub",
    mihanwebhost = "mihanwebhost",
    fitamin = "fitamin",
    ivahid = "ivahid",
    cafeamoozeshgah = "cafeamoozeshgah",
    khanoumi = "khanoumi",
    portal = "portal",
    arongroups = "arongroups",
    taraz = "taraz",
    zhaket = "zhaket",
    azaronline = "azaronline",
    arazcloud = "arazcloud",
    poonehmedia = "poonehmedia",
    kidzy = "kidzy",
    khanomsin = "khanomsin",
    techranco = "techranco",
    tlyn = "tlyn",
    parspack = "parspack",
    pdf = "pdf",
    ipresta = "ipresta",
    irancell = "irancell",
    farazsms = "farazsms",
    raygansms = "raygansms",
    zarinpal = "zarinpal",
    melipayamak = "melipayamak",
    mopon = "mopon",
    clickaval = "clickaval",
    alomohtava = "alomohtava",
    behtarinideh = "behtarinideh",
    podium = "podium",
    infogramacademy = "infogramacademy",
    idpay = "idpay",
    payamgostar = "payamgostar",
    nabzemarketing = "nabzemarketing",
    transis = "transis",
    bitpin = "bitpin",
    fardaname = "fardaname",
    roshadent = "roshadent",
    activeidea = "activeidea",
    doctoryab = "doctoryab",
    paziresh24 = "paziresh24",
    webkima = "webkima",
    sellfree = "sellfree",
    dargi = "dargi",
    quera = "quera",
    karlancer = "karlancer",
    hitalki = "hitalki",
    azki = "azki",
    mosbatesabz = "mosbatesabz",
    karokasb = "karokasb",
    mizbanfa = "mizbanfa",
    jadvalyab = "jadvalyab",
    basalam = "basalam",
    ghafaridiet = "ghafaridiet",
    myket = "myket",
    samanehha = "samanehha",
    meghdadit = "meghdadit",
    sheypoor = "sheypoor",
    divar = "divar",
    dotic = "dotic",
    ekhtebar = "ekhtebar",
    qavanin = "qavanin",
    rcmajlis = "rcmajlis",
    shenasname = "shenasname",
    labourlaw = "labourlaw",
    sistani = "sistani",
    agorgani = "agorgani",
    shoragc = "shoragc",
    saafi = "saafi",
    extern = "extern",
    rastineh = "rastineh",
    drsaina = "drsaina",
    wikishia = "wikishia",
    /* javabyab="javabyab",
        asreertebat = "asreertebat",
        ictnn = "ictnn",
        techna = "techna",
        itpress = "itpress",
        jamaran = "jamaran",
        aryanews = "aryanews",
        sinapress = "sinapress",
        ion = "ion",
        shomalnews = "shomalnews",
        nakhostnews = "nakhostnews",
        wnn = "wnn",
        berasad = "berasad",
        artanpress = "artanpress",
        tasna = "tasna",
        manbaekhabar = "manbaekhabar",
        melatebidaronline = "melatebidaronline",
        hamraznews = "hamraznews",
        partianemrooz = "partianemrooz",
        sedanews = "sedanews",
        bamdad = "bamdad",
        hajnews = "hajnews",
        armaneghtesadi = "armaneghtesadi",
        raby = "raby",
        iranetavana = "iranetavana",
        ekhtebar = "ekhtebar",
        tehranpardis = "tehranpardis",
        khabartehran = "khabartehran",
        otaghnews = "otaghnews",
        asretech = "asretech",
        sarkhat = "sarkhat",
        afraca = "afraca",*/
}

export interface IntfGlobalConfigs {
    debugVerbosity?: number,
    showInfo?: boolean,
    debugDB?: boolean,
    showWarnings?: boolean,
    db?: string,
    maxConcurrent?: number,
    delay?: number,
    corpora?: string,
    proxies?: string[] | string,
    hostIP?: string,
    logPath?: string,
    compact?: boolean
}

export enum enuTextType {
    paragraph = "p",
    caption = "caption",
    cite = "cite",
    h1 = "h1",
    h2 = "h2",
    h3 = "h3",
    h4 = "h4",
    alt = "alt",
    link = "link",
    ilink = "ilink",
    li = "li",
    blockquote = "blockquote"
}

export interface IntfKeyVal { [key: string]: string }
export interface IntfText { text: string, type: enuTextType, ref?: string }
export interface IntfComment { text: string, author?: string, date?: string }
export interface IntfImage { src: string, alt?: string }
export interface IntfContentHolder { texts: IntfText[], images: IntfImage[] }

export interface IntfPageContent {
    url: string,
    category?: string,
    article?: {
        date?: string,
        title?: string,
        aboveTitle?: string,
        subtitle?: string,
        summary?: string,
        content?: IntfText[],
        comments?: IntfComment[]
        images?: IntfImage[],
        tags?: string[],
    }
    links: string[],
}

export interface IntfDocFilecontent {
    url: string,
    category: string | IntfMappedCatgory,
    date?: string,
    title?: string,
    aboveTitle?: string,
    subtitle?: string,
    summary?: string,
    content?: IntfText[],
    comments?: IntfComment[]
    images?: IntfImage[],
    tags?: string[],
}

export enum enuMajorCategory {
    News = "News",
    Literature = "Literature",
    Forum = "Forum",
    Undefined = "Undefined",
    Weblog = "Weblog",
    Wiki = "Wiki",
    SocialMedia = "SocialMedia",
    Doc = "Doc"
}

export enum enuMinorCategory {
    Political = "Political",
    FAQ = "FAQ",
    Social = "Social",
    Health = "Health",
    Medical = "Medical",
    Economy = "Economy",
    Culture = "Art&Culture",
    Consultation = "Consultation",
    Sport = "Sport",
    ScienceTech = "Science&Tech",
    Job = "Job",
    SEO = "SEO",
    Journalism = "Journalism",
    Undefined = "Undefined",
    Generic = "Generic",
    Multimedia = "Multimedia",
    Talk = "Talk",
    Discussion = "Discussion",
    Poem = "Poem",
    Text = "Text",
    Local = "Local",
    Religious = "Religious",
    Law = "Law",
    LifeStyle = "LifeStyle",
    Game = "Game",
    Education = "Education",
    Literature = "Literature",
    Historical = "Historical",
    University = "University",
    Defence = "Defence",
    Fun = "Fun",
    Weather = "Weather",
    Advert = "Advert",
    CryptoCurrency = "CryptoCurrency",
    IT = "IT",
    ICT = "ICT",
    DigitalMarketing = "DigitalMarketing",
    Tourism = "Tourism",
}

export enum enuSubMinorCategory {
    Game = "Game",
    GoldSilver = "GoldSilver",
    Reportage = "Reportage",
    Security = "Security",
    Mobile = "Mobile",
    Robotic = "Robotic",
    Hardware = "Hardware",
    Network = "Network",
    Software = "Software",
    Chemical = "Chemical",
    Language = "Language",
    Car = "Car",
    Energy = "Energy",
    Gadgets = "Gadgets",
    AI = "AI",
    Intl = "Intl",
    Accident = "Accident",
    Art = "Art",
    Agriculture = "Agriculture",
    TV = "TV",
    Radio = "Radio",
    Book = "Book",
    Celebrities = "Celebrities",
    Cooking = "Cooking",
    Cinema = "Cinema",
    Documentry = "Documentry",
    Music = "Music",
    Media = "Media",
    Theatre = "Theatre",
    Football = "Football",
    Basketball = "Basketball",
    Ball = "Ball",
    Wrestling = "Wrestling",
    Martial = "Martial",
    Weightlifting = "Weightlifting",
    Women = "Women",
    Animals = "Animals",
    Police = "Police"
}

export interface IntfMappedCatgory {
    major: enuMajorCategory,
    minor?: enuMinorCategory,
    subminor?: enuSubMinorCategory | enuMinorCategory
}

export interface IntfProxy {
    agent: SocksProxyAgent,
    port: string
}

export interface IntfSelectorFunction {
    (article: HTMLElement, fullHtml: HTMLElement, url: URL): HTMLElement | null | undefined
}

export interface IntfIsValidFunction {
    (article: HTMLElement, fullHtml: HTMLElement): boolean
}

export interface IntfSelectAllFunction {
    (article: HTMLElement, fullHtml: HTMLElement): HTMLElement[] | undefined
}

export interface IntfIgnoreTextElementFunction {
    (el: HTMLElement, index: number, allElements: HTMLElement[]): boolean
}
export interface IntfGetCommentsByAPI {
    (url: URL, reParams: IntfRequestParams): Promise<IntfComment[]>
}

export interface IntfSelectorToString {
    (element: HTMLElement, fullHtml?: HTMLElement): string
}

export interface IntfURLNormaliziztionConf {
    extraValidDomains?: string[]
    extraInvalidStartPaths?: string[],
    ignoreContentOnPath?: string[],
    removeWWW?: boolean,
    pathToCheckIndex?: number | null
    validPathsItemsToNormalize?: string[]
}

export interface IntfProcessorConfigs {
    selectors?: {
        article?: string | IntfSelectorFunction,
        aboveTitle?: string | IntfSelectorFunction,
        title?: string | IntfSelectorFunction,
        subtitle?: string | IntfSelectorFunction,
        summary?: string | IntfSelectorFunction,
        content?: {
            main?: string | IntfSelectAllFunction,
            alternative?: string | IntfSelectAllFunction,
            textNode?: string | IntfSelectorFunction,
            alterTextContent?: IntfSelectorToString,
            ignoreTexts?: string[] | RegExp[],
            ignoreNodeClasses?: string[] | IntfIsValidFunction,
        },
        comments?: {
            container?: string | IntfSelectAllFunction,
            datetime?: string | IntfSelectorToString,
            author?: string | IntfSelectorFunction,
            text?: string | IntfSelectorFunction
        } | IntfGetCommentsByAPI,
        tags?: string | IntfSelectAllFunction,
        datetime?: {
            conatiner?: string | IntfSelectorFunction,
            splitter?: string | IntfSelectorToString,
            isGregorian?: boolean
            acceptNoDate?: boolean
        }
        category?: {
            selector?: string | IntfSelectAllFunction,
            startIndex?: number,
        }
    },
    url?: IntfURLNormaliziztionConf
    basePath?: string
    preHTMLParse?: (html: string) => string
}

